<h1>IxTheo A-Z</h1>
<ul>
    <li><a href="docs/ixtheo-beacon.txt">Beacon</a><br/>Die mit der GND-Nummer ausgezeichneten Katalogisate des IxTheo stehen im Beaconformat zur Verfügung und können in andere Datenbanken verlinkt werden.<br/>Weitere Infos siehe: <a href="https://de.wikipedia.org/wiki/Wikipedia:BEACON">Wikipedia</a> oder <a href="http://gbv.github.io/beaconspec/beacon.html">Github</a></li>
    <li><a href="docs/ixtheo-bible-search_de.pdf">Bibelstellensuche</a></li>
    <li><a href="docs/Bible_abbreviation.pdf">Bibelstellen: Abkürzungen</a></li>
    <li><a href="docs/ixtheo-pda.pdf">Benutzergesteuerte Erwerbung</a><br/>siehe PDA</li>
    <li><a href="docs/ixtheo-serials.pdf">Erwerbung von Reihen und Zeitschriften</a><br/>Liste der Reihen und Fortsetzungen, die im Rahmen des FID Theologie dauerhaft und vollständig von der UB Tübingen gekauft werden.</li>
    <li><a href="docs/ixtheo-erschliessungskonzept.pdf">Erschließungskonzept</a><br/>Inhaltliches Erschließungskonzept für Monographien, Aufsätze etc.</li>
    <li><a href="docs/ixtheo-journals.pdf">IxTheo-Zeitschriften</a><br/>Liste der momentan und zukünftig im IxTheo ausgewerteten Zeitschriften.</li>
    <li><a href="docs/ixtheo-pda.pdf">PDA</a><br/>NutzerInnen können den Kauf von Einzelmonographien, die an ihren Standorten nicht vorhanden bzw. nicht über Fernleihe beschaffbar sind, direkt im IxTheo veranlassen.</li>
    <li><a href="docs/TAD.pdf">TAD</a><br/>Lokaler Aufsatzlieferdienst (nur für WissenschaftlerInnen der Universität Tübingen).</li>
</ul>