
<div class="col-md-12" style="text-align:justify;">
    <h2>Liebe Nutzer des Index Theologicus,</h2>
    <div class="post">
        <p>wir freuen uns, Ihnen die Alpha-Version des neuen IxTheo vorstellen zu können.</p>
        <p>Der neue IxTheo ist eine umfassende Bibliographie für Theologie und Religionswissenschaft. Es können nun
            neben Aufsätzen auch Monographien, Datenbanken und relevante Internetlinks recherchiert werden. Neu ist
            auch, dass die Daten ausgewählter Rezensionsorgane in den IxTheo einbezogen werden. Wenn es lizenzrechtlich
            möglich ist, kann direkt auf die Volltexte der Aufsätze, Rezensionen und Bücher zugegriffen werden.</p>
        <p>Der neue IxTheo bleibt weiterhin ein kostenloses open access Angebot an die weltweite Fachcommunity.
            Herausgeber des IxTheo sind die Universitätsbibliothek Tübingen sowie die Evangelisch-Theologische Fakultät
            Tübingen und die Katholisch-Theologische Fakultät Tübingen.</p>
        <p>Wir bitten um Verständnis, dass in einer Alpha-Version noch nicht alles fehlerfrei funktioniert. Wir wünschen
            Ihnen viel Freude beim Entdecken des neuen IxTheo und sind dankbar über Ihr Feedback!</p>
    </div>
</div>
<?
$panelId = 0;
$panelClass = "panel-default";
$panelWidth = "col-md-6";
?>
<h2 class="col-md-12 panel-group">IxTheo entdecken</h2>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-search"></i> Suchen
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <p>Starten Sie eine Suche über alle im IxTheo enthaltenen Titel, indem Sie auf den Button „Suchen“
                    klicken. Sie erhalten die volle Trefferzahl mit mehr als 1,6 Mio Titeln.</p>

                <p>Grenzen Sie die Suche nun nach gewissen Kriterien ein, indem Sie entsprechende Facetten
                    auswählen.
                    Sie können z.B. gezielt den Medientyp „Elektronisch“, die Medienart „Aufsatz“ und die Sprache
                    „Deutsch“ auswählen. Nun ist die Menge der Titel auf etwa 3000 Titel eingeschränkt</p>

                <h3>Inhaltliche Suche</h3>
                <h4>IxTheo-Klassifikation</h4>
                <p> Nutzen Sie dazu die erweiterte Suche, indem Sie unter dem Suchschlitz auf „Erweitert“ klicken.
                    Dort
                    finden Sie u.a. die IxTheo-Klassifikationen. Wählen Sie entsprechende Klassen durch Anklicken
                    aus.
                    Mehrere Klassen können als Block durch das Halten der Umstell-Taste beim Anklicken markiert
                    werden.
                    Mehrere einzelne Facetten werden durch das Halten der Kommando-Taste beim Anklicken
                    markiert.</p>
                <p>Starten Sie durch Klick auf „Suche“ nun eine gezielte Suche nach den ausgewählten IxTheo
                    Klassen.</p>

                <h3>Verbale Suchbegriffe</h3>
                <p>Tippen Sie den Suchbegriff in den Suchschlitz und belassen Sie den Suchaspekt auf „Alle Felder“.
                    Der
                    eingegebene Begriff wird dann in allen Suchfeldern gesucht.</p>
                <p>Für eine inhaltliche Suche ist die Auswahl des Suchaspektes „Schlagwort“ von großem Nutzen. Hier
                    werden intellektuell vergebene Schlagwörter und Schlagwortfolgen duchsucht.</p>
            </div>
        </div>
    </div>
</div>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-list"></i> Browsen
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse ">
            <div class="panel-body">
                <p>Der neue IxTheo stellt drei verschiedene Arten des Browsens zur Verfügung. Sie finden den
                    Browsing
                    Modus durch Klick auf „Browsing“ unterhalb des Suchschlitzes.</p>

                <h3>IxTheo-Themen Browsing</h3>
                <p>Es öffnet sich ein weiterer Suchschlitz, in den Sie Ihren Suchbegriff eingeben. Er dient als
                    Startpunkt des Browsens.</p>
                <p>Beispiel 1: geben Sie den Begriff „Gott“ ein. Sie sehen dann eine spezielle Liste mit
                    Schlagwortfolgen, in denen der Begriff Gott vorkommt.</p>
                <p>Beispiel 2: geben den Begriff „Gott“ und „Bibel“ ein. Sie sehen dann eine spezielle Liste mit
                    Schlagwortfolgen, in denen der Begriff „Gott“ und „Bibel“ vorkommt.</p>
                <p>Wenn Sie rechts oben auf der Website die Sprache auf Englisch ändern, werden die Begriffe im
                    Englischen angezeigt, wenn sie in der Sprachkonkordanz vorhanden sind.</p>

                <h3>Katalogbrowsen</h3>
                <p>Die Standard-Browsing Funktion der Software des IxTheo (VuFind) ermöglicht das Browsen in
                    verschiedenen Feldern: DDC-Klassifikation, IxTheo-Klassifikation, Thema (Schalgwort), Verfasser
                    und
                    Verlag. In einem weiteren Schritt kann hier das Browsing durch andere Felder strukturiert und
                    sortiert werden.</p>
                <p>Beispiel: Wählen Sie „Verfasser“, dann „Nach IxTheo-Klassifikation“, dann „HB Altes Testament“
                    aus.
                    Sie sehen dann eine Liste von Autoren, die im Bereich des Alten Testaments publiziert haben,
                    sortiert nach Häufigkeit der Titel im IxTheo.</p>

                <h3>Alphabetisch browsen</h3>
                <p>Hier können Sie bestimmen, an welcher Stelle des Alphabets Sie in das Browsing einsteigen wollen.
                    Nach der Auswahl des Browsingaspektes (möglich sind „Thema“, Verfasser, Titel und
                    DDC-Klassifikation) geben Sie den Buchstaben ein, ab dem das Browsing starten soll.</p>
                <p>Beispiel 1: Wählen Sie „Nach Verfasser“ und geben Sie ein: ab „Z“. Es werden dann alle Verfasser
                    aufgelistet, die mit dem Buchstaben Z beginnen.</p>
                <p>Beispiel 2: Wählen Sie „Nach Titel“ und geben Sie ein: ab „Tr“. Es werden dann alle Titel
                    aufgelistet, die mit der Buchstabenfolge Tr beginnen.</p></div>
        </div>
    </div>
</div>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-child"></i> Personalisierung
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <p>Viele nützliche Funktionen stehen Ihnen zur Verfügung, wenn Sie einen persönlichen Account
                    anlegen.
                    Nach einer einmaligen Registrierung können Sie sich in Ihren Account einloggen. Um sich zu
                    registrieren oder einzuloggen klicken Sie auf den Link „Login“ rechts oben.</p>
                <p>Durch Klick auf „Ihr Konto“ kommen Sie in Ihren personalisierten Bereich. Dort stehen Ihnen u.a.
                    folgende Funktionen zur Verfügung:</p>

                <h3>Alerting-Funktion</h3>
                <p>Die Alerting Funktion unterrichtet Sie über neu erschienene Aufsätze aus Zeitschriften und neu
                    erschienene Bände in Reihen und Fortsetzungen. Sie können frei entscheiden, in welchen Fällen
                    Sie
                    eine Benachrichtigung wünschen.</p>
                <p>Um eine Zeitschrift oder eine Reihe für das Alerting auszuwählen, müssen Sie die Gesamtaufnahme
                    der
                    Zeitschrift oder Reihe subskribieren. Klicken Sie dazu auf das Symbol "Glocke", die Sie rechts
                    im
                    entsprechenden Datensatz sehen. In Ihrem Konto können Sie die Subskriptionen verwalten.</p>

                <p>Beispiel 1: Um die Theologische Quartalschrift zu subskribieren, recherchieren Sie nach dem Titel
                    der
                    Reihe oder geben Sie in den Suchschlitz die Abkürzung „ThQ“ ein. Wählen Sie im Anschluss unter
                    Medienart die Facette Zeitschrift aus. Sie haben 2 Treffer: zum einen die Gesamtaufnahme der
                    gedruckten, zum anderen die Gesamtaufnahme der elektronischen Zeitschrift der ThQ. In diesem
                    Fall
                    ist es sinnvoll, beide Medienarten zu subskribieren.</p>

                <p>Beispiel 2: Um die Reihe „Wissenschaftliche Untersuchungen zum Neuen Testament“ zu subskribieren,
                    recherchieren Sie nach dem Titel der Reihe oder geben Sie in den Suchschlitz die Abkürzung
                    „WUNT“
                    ein. Sie haben mehrere Treffer. Subskribieren Sie die gewünschte Reihe durch Klick auf das
                    Symbol
                    „Glocke“.</p>

                <p>Wir werden uns bemühen, die Auswahl der Zeitschriften und Reihen für das Alerting zukünftig
                    bequemer
                    für Sie zu gestalten. Angedacht ist, dass Sie Zeitschriften, die im IxTheo ausgewertet werden,
                    geordnet nach Disziplinen im Block subskribieren können.</p>

                <h3>Suchanfragen speichern</h3>
                <p>Ihre aktuellen Suchanfragen werden in der Suchhistorie temporär gespeichert. Wenn Sie die
                    Suchanfragen dauerhaft verwenden wollen, können Sie sie in Ihrem Konto abspeichern. Sie stehen
                    dann
                    in Ihrem Konto dauerhaft zur Verfügung und können durch Anklicken erneut ausgeführt werden. Das
                    lohnt sich für komplexe Abfragen oder für Themen, an denen Sie kontinuierlich interessiert sind.
                    Auf
                    diese Weise entdecken Sie leicht die neu erschienene Literatur zu einem bestimmten Thema oder
                    Themengebiet.</p>

                <h3>Favoriten speichern</h3>
                <p>Speichern Sie interessante Titel direkt in Ihrem Konto ab. Damit stehen Sie Ihnen dauerhaft zur
                    Verfügung und Sie müssen nicht viel Zeit mit dem Wiederfinden verwenden. Damit die Favoriten
                    geordnet werden können, werden Sie in Listen gespeichert, die Sie definieren können. So können
                    interessante Titel gewissen Forschungsprojekten oder Themen zugeordnet werden.</p>
                <p>Aus Ihrem Konto heraus können Sie Favoriten exportieren, per Mail verschicken oder
                    Ausdrucken.</p>
            </div>
        </div>
    </div>
</div>
