<p>Sehr geehrter IxTheo-Nutzer,</p>

<p>im Patron Driven Acquisition (PDA) Programm des Fachinformationsdienstes (FID) Theologie können Sie die Beschaffung von Büchern veranlassen, die Sie für Ihre Forschung benötigen und bisher noch nicht für die Ausleihe zur Verfügung stehen.</p>

<p>Falls Sie im unteren Feld eine Lieferadresse angeben, werden wir Ihnen das Buch direkt zusenden. Bitte beachten Sie, dass ein Direktlieferdienst nur innerhalb Deutschlands erfolgen kann. Wenn Sie aus anderen Ländern kommen, müssen Sie das gewünschte Buch mittels Fernleihe bestellen.</p>

<p>Was sind die nächsten Schritte?</p>
<ol>
    <li>Wir werden nun versuchen, das gewünschte Buch zu erwerben
    <li> Wenn das Buch nicht erworben werden kann, informieren wir Sie per Mail
    <li> Nach Eingang des erworbenen Buches in de UB Tübingen versenden wir das Buch direkt an Sie, wenn Sie eine Lieferadresse angeben haben. 
    <li> Nach Ablauf der Ausleihfrist schicken Sie das Buch an uns zurück. Details finden Sie im gelieferten Buch.
    <li> Wenn Sie keine Lieferadresse angeben, informieren wir Sie über den Eingang des Buches in der UB Tübingen. 
         Sie können dann unmittelbar eine Fernleihbestellung aufgeben. 
</ol>
<p>Wie lange können Sie das Buch ausleihen?<br>
Die Ausleihfrist beträgt 4 Wochen</p>

<p>Sie sind nun im Begriff, eine Beschaffung für folgendes Buch auszulösen:</p>
