Was sind die nächsten Schritte?
    1.) Wir werden nun versuchen, das gewünschte Buch zu erwerben
    2.) Wenn das Buch nicht erworben werden kann, informieren wir Sie per Mail
    3.) Nach Eingang des erworbenen Buches in de UB Tübingen versenden wir das Buch direkt an Sie, wenn Sie eine Lieferadresse angeben haben. 
    4.) Nach Ablauf der Ausleihfrist schicken Sie das Buch an uns zurück. Details finden Sie im gelieferten Buch.
    5.) Wenn Sie keine Lieferadresse angegeben haben, informieren wir Sie über den Eingang des Buches in der UB Tübingen. 
        Sie können dann unmittelbar eine Fernleihbestellung aufgeben. 
