<?= $this->flashmessages() ?>
<?php if (!empty($this->pdasubscription)) { ?>
    <?=$this->render($this->infoText);?>
    <form id="edit-save-form" class="form-horizontal" method="post"
          action="<?= $this->recordLink()->getActionUrl($this->driver, 'PDASubscribe') ?>" name="pdasubscribeRecord"
          data-lightbox-onclose="checkSubscribeStatuses();">
        <input type="hidden" name="action" value="pdasubscribe"/>
        <input class="btn btn-primary" type="submit" value="<?= $this->transEsc('PDASubscribe') ?>"/>
    </form>
<?php } else { ?>
    <p><?=$this->transEsc("Subscription exists for this document");?>.</p>
    <form id="edit-save-form" class="form-horizontal" method="post"
          action="<?= $this->recordLink()->getActionUrl($this->driver, 'PDASubscribe') ?>" name="pdaunsubscribeRecord"
          data-lightbox-onclose="checkPDASubscribeStatuses();">
        <input type="hidden" name="action" value="pdaunsubscribe"/>
        <input class="btn btn-danger" type="submit" value="<?= $this->transEsc("PDAUnsubscribe");?>"/>
    </form>
<?php } ?>
