<?= $this->flashmessages() ?>
<?php if (!empty($this->subscription)) { ?>
    <p>Quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel
        eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla
        facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue
        duis dolore te feugait nulla facilisi.</p>
    <p>Option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet,
        consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat
        volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip
        ex ea commodo consequat. </p>
    <p>In vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis. </p>
    <form id="edit-save-form" class="form-horizontal" method="post"
          action="<?= $this->recordLink()->getActionUrl($this->driver, 'Subscribe') ?>" name="subscribeRecord"
          data-lightbox-onclose="checkSubscribeStatuses();">
        <input type="hidden" name="action" value="subscribe"/>
        <input class="btn btn-primary" type="submit" value="<?= $this->transEsc('Subscribe') ?>"/>
    </form>
<?php } else { ?>
    <p> Subscription exists for this document. </p>
    <form id="edit-save-form" class="form-horizontal" method="post"
          action="<?= $this->recordLink()->getActionUrl($this->driver, 'Subscribe') ?>" name="unsubscribeRecord"
          data-lightbox-onclose="checkSubscribeStatuses();">
        <input type="hidden" name="action" value="unsubscribe"/>
        <input class="btn btn-danger" type="submit" value="<?= $this->transEsc('Unsubscribe') ?>"/>
    </form>
<?php } ?>
