<style>
    .read-more-state {
        display: none;
    }

    .read-more-target {
        opacity: 0;
        max-height: 0;
        font-size: 0;
        transition: .25s ease;
    }

    .read-more-state:checked ~ .read-more-wrap .read-more-target {
        opacity: 1;
        font-size: inherit;
        max-height: 999em;
    }


    .read-more-state ~ .read-more-trigger:before {
        content: 'Mehr';
    }

    .read-more-state:checked ~ .read-more-trigger:before {
        content: 'Weniger';
    }

    .read-more-trigger {
        cursor: pointer;
        display: inline-block;
        padding: 0 .5em;
        color: #666;
        font-size: .9em;
        line-height: 2;
        border: 1px solid #ddd;
        border-radius: .25em;
    }
</style>


<div class="col-md-12" style="text-align:justify;">
    <h2>Liebe Nutzer von RelBib,</h2>
    <div class="post">
        <p>Wir freuen uns, Ihnen die &sbquo;Religionswissenschaftliche Bibliografie&lsquo;, kurz RelBib, vorstellen zu können. Sie ist die Alpha-Version einer vom Fachinformationsdienst (FID) &sbquo;Religionswissenschaft&lsquo; betreuten umfassenden bibliografischen Datenbank.</p>
        <p>Die Datenbank enthält derzeit <b><? include(dirname(__DIR__) . '/includes/relbib_journals_total.txt')?></b> Zeitschriften der Allgemeinen und Vergleichenden Religionswissenschaft, der Religionsgeschichte und einiger anderer kulturwissenschaftlicher Fach- und Themengebiete. Die Anzahl der Zeitschriften, deren Aufsätze in der Datenbank einzeln nachgewiesen werden, beträgt derzeit etwa ein Fünftel. Es werden sukzessive weitere Zeitschriften in die Aufsatzerschließung übernommen.  Aus der alphabetischen <a href="<?='https://'.$_SERVER['SERVER_NAME'] . '/relbib_journals.pdf'?>" target="_blank"><b>Übersicht der Zeitschriften</b></a> können Sie sich über den Stand der Auswertung informieren. Außer Zeitschriften(artikeln) enthält die Datenbank Nachweise zu religionswissenschaftlich relevanten Monografien.</p> 
        <p>Über den Link &bdquo;Verfügbarkeit&rdquo; kann rasch abgefragt werden, ob und wo eine Zeitschrift, ein Aufsatz oder ein Buch verfügbar ist. Wenn es lizenzrechtlich möglich ist, kann auf elektronisch vorliegende Texte direkt zugegriffen werden.</p>
        <p>RelBib ist ein kostenloses open access Angebot an die weltweite Fachcommunity der Religionswissenschaft. Herausgeber von RelBib ist die Universitätsbibliothek Tübingen. RelBib entsteht in Zusammenarbeit mit <a href="https://ixtheo.de" target="_blank">IxTheo</a>, der theologischen Datenbank, die vom FID Theologie entwickelt und betreut wird. Durch die Zusammenarbeit können Synergien genutzt werden. </p>
        <p>Wir bitten um Verständnis, dass in einer Alpha-Version noch nicht alles fehlerfrei funktioniert. Wir wünschen
            Ihnen viel Freude beim Entdecken von RelBib und sind dankbar über Ihr Feedback!</p>
    </div>
</div>
<?
$panelId = 0;
$panelClass = "panel-default";
$panelWidth = "col-md-6";
?>
<h2 class="col-md-12 panel-group">RelBib entdecken</h2>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-search"></i> Suchen
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-1" />
                <div class="read-more-wrap">
                    <p>Die volle Trefferzahl aller derzeit in RelBib vorhandenen Einträge erhalten Sie, 
                       wenn Sie – ohne weitere Eingabe – den Button „Suchen“ klicken. 
                    <div class="read-more-target">
                           Die angezeigte Trefferzahl ist tagesgenau, das jüngste Erscheinungsdatum steht oben.
                           Nun können Sie die Suche anhand verschiedener Kriterien eingrenzen, indem Sie entsprechende Facetten auswählen.</p>
                        <p>
                           Klicken Sie z.B. bei <strong>Medienart</strong> auf <em>Buch</em>, erhalten Sie die derzeit im System befindlichen 
                           Monografien mit einer religionswissenschaftlichen Kennung. Eine weitere Auswahl z.B. unter <strong>Medientyp</strong> 
                           <em>Elektronisch</em> zeigt Ihnen die elektronisch verfügbaren Bücher an.</p>
                        <p>Auch <em>inhaltlich</em> können Sie den Bestand <em>filtern</em>: Wählen Sie „RelBib Klassifikation“ oder „DDC-Klassifikation“ 
                           oder den Filter „Thema (Schlagwort)“ und klicken Sie eine oder mehrere für Sie interessante Kategorien an.</p>
    
                        <h3>Einfache Suche</h3>
                        <p>
                           Wenn Sie nach dem <strong>konkreten</strong> Titel einer Zeitschrift, eines Buches oder eines Aufsatzes oder nach einem 
                           <strong>bestimmten</strong> Autor suchen, geben Sie 1-3 Begriffe im Suchschlitz ein. Die Suche läuft dann über „Alle Felder“. 
                           Sollte dies zu unbefriedigendem Ergebnis  führen, können Sie auch die Felder über das Auswahlmenu ändern, also z.B. 
                           nur über das Titelfeld suchen. Falls Sie die ISBN eines Buches oder die ISSN einer Zeitschrift kennen, wählen sie 
                           im Auswahlmenü „ISSN / ISBN“ und geben die entsprechende Nummer ein. So erhalten Sie das Gesuchte ohne weitere Verzögerung.</p>
                        <p>
                           Wenn Sie <em>verschiedene Suchfelder</em> miteinander kombinieren möchten, nutzen Sie die „Erweiterte Suche“. 
                           Diese erreichen Sie über den Link unterhalb des großen Suchschlitzes.</p>
                        <h3>Inhaltliche Suche </h3>
                        <h4>Verbale Suchbegriffe</h4>
                        <p>Tippen Sie den Suchbegriff in den Suchschlitz und belassen Sie den Suchaspekt auf „Alle Felder“.
                            Der eingegebene Begriff wird dann in allen Suchfeldern gesucht.</p>
                        <p>
                           Sollte die Trefferzahl zu groß oder zu unspezifisch sein, wählen Sie den Suchaspekt „Schlagwort“ für die Suche nach Ihrem 
                           Begriff aus. Schlagwörter und Schlagwortfolgen sind normierte Begriffe die von uns intellektuell vergeben werden. 
                           Mit einer Schlagwortsuche erhalten Sie auch Treffer die nicht unbedingt das von Ihnen eingegebene Wort, sondern u.U. ein 
                           (Quasi-)Synonym oder einen verwandten Begriff enthalten. Weiteres zur Suche nach Schlagwortfolgen siehe unter „Browsing“.</p>
                        <h4>Suche über die RelBib-Klassifikation</h4>
                        <p>Gehen sie zu „Erweiterte Suche“ und wählen Sie bei „RelBib Notation“ ein oder mehrere Gebiete aus. Für mehrere Gebiete halten 
                           Sie bei einer Windows-Tastatur die „Strg-Taste", bei einer Mac-Tastatur die „Kommando"-Taste gedrückt. Klicken Sie dann auf „Suche“</p>
                        <p>Die so erhaltenen Ergebnisse können sie nun mit Hilfe von weiteren Suchbegriffen oder Filtereinstellungen präzisieren.</p>  
                     </div>
                </div>
                <label for="post-1" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-list"></i> Browsen
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse ">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-2" />
                <div class="read-more-wrap">
                    <p>RelBib stellt drei verschiedene Arten des Browsens zur Verfügung. Sie finden den
                        Browsing
                        Modus durch Klick auf „Browsen“ unterhalb des Suchschlitzes.</p>
                    <div class="read-more-target">
                        <!-- Needed since otherwise the More-Button gets confused immediately before a heading -->
                        <div style="height: 0px;">&emsp;</div>
                        <h3>Thema Browsing</h3>
                        <p>Es öffnet sich ein weiterer Suchschlitz, in den Sie Ihren Suchbegriff eingeben. Er dient als
                            Startpunkt des Browsens.</p>
                        <p>Beispiel 1: geben Sie den Begriff „Islam“ ein. Sie sehen dann eine spezielle Liste mit
                            Schlagwortfolgen, die den Begriff Islam enthalten.</p>
                        <p>Beispiel 2: geben den Begriff „Islam“ und „Gott“ ein. Nun erscheint eine spezielle Liste mit
                            Schlagwortfolgen, die beide Begriffe „Islam“ und „Gott“ vorkommt.</p>
                        <p>Wenn Sie rechts oben auf der Website die Sprache auf Englisch ändern, werden die Begriffe im
                            Englischen angezeigt, wenn sie in der Sprachkonkordanz vorhanden sind.</p>

                        <h3>Browsen nach Kategorien („Katalog“ browsen)</h3>
                        <p>Die Standard-Browsing Funktion der Software von RelBib (VuFind) ermöglicht das Browsen in
                            verschiedenen Feldern: DDC-Klassifikation, RelBib-Klassifikation, Thema (Schlagwort), Verfasser
                            und Verlag. In weiteren Schritten kann hier das Browsing durch andere Felder eingeschränkt werden.</p>
                        <p>Beispiel: Klicken Sie z. B. auf „DDC Klassifikation“, dann auf „200 Religion“, dann 210 „Philosophy and Theory of religion“. 
                           Im Folgenden werden noch weitere Unterfelder angezeigt, die Sie gegebenenfalls auswählen können. Auf jedem der Felder befindet 
                           sich jeweils rechts unten ein Button, der die Zahl der Titel, die mit dieser Kategorie verknüpft sind, anzeigt.
                           Klicken Sie auf „Datensätze ansehen“ und Sie erhalten die Liste der Titel.</p>

                        <h3>Alphabetisch browsen</h3>
                        <p>Hier können Sie bestimmen, an welcher Stelle des Alphabets Sie in das Browsing einsteigen wollen.
                            Nach der Auswahl des Browsingaspektes (möglich sind „Thema“, Verfasser, Titel und
                            DDC-Klassifikation) geben Sie den Buchstaben ein, ab dem das Browsing starten soll.</p>
                        <p>Beispiel: Wählen Sie „Nach Thema“ und geben Sie ein: ab „rel“. Es werden dann alle Schlagwörter
                            aufgelistet, die mit dem Buchstaben rel beginnen.</p>
                        <p>Eine solch alphabetisches browsing kann auch hilfreich sein, wenn Sie die Schreibweise eines Autorennamen nicht richtig erinnern. 
                           Beispiel: Wählen Sie dazu „Nach Verfasser“ und geben Sie ein: ab „Tr“. Es werden dann alle Verfasser aufgelistet, deren Nachnamen mit der 
                           Buchstabenfolge Tr beginnen.</p>
                        <p>Übrigens: Einen Browsing-Button gibt es auch bei jeder Monografie, die mit Schlagwörtern versehen wurde. Klicken Sie auf den Button 
                           <strong>„B“</strong> links neben den Schlagwörtern und Sie erhalten weitere Titel, die dieselbe Schlagwortfolge aufweisen.</p>
                    </div>
                </div>
                <label for="post-2" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-child"></i> Meine RelBib
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-3" />
                <div class="read-more-wrap">
                    <p>Viele nützliche Funktionen stehen Ihnen zur Verfügung, wenn Sie einen persönlichen Account
                        anlegen.
                        Nach einer einmaligen Registrierung können Sie sich in Ihren Account einloggen.
                    <div class="read-more-target">
                        Um sich zu registrieren oder einzuloggen klicken Sie auf den Link „Login“ rechts oben.</p>
                        <p>Durch Klick auf „Ihr Konto“ kommen Sie in Ihren personalisierten Bereich. Dort stehen Ihnen u.a.
                            folgende Funktionen zur Verfügung:</p>

                        <h3>Neuerscheinungen abonnieren (Alerting-Funktion)</h3>
                        <p>Mit dieser Funktion können Sie sich über neu erschienene Aufsätze aus Zeitschriften und neu erschienene Bände in Reihen 
                           und Fortsetzungen benachrichtigen lassen. Sie entscheiden selbst, in welchen Fällen Sie eine Benachrichtigung wünschen.</p>
                        <p>Um eine Zeitschrift oder eine Reihe für das Alerting auszuwählen, müssen Sie die Gesamtaufnahme
                           der Zeitschrift oder Reihe subskribieren. Klicken Sie dazu auf das Symbol "Glocke", die Sie rechts
                           im entsprechenden Datensatz sehen. In Ihrem Konto können Sie die Subskriptionen verwalten.</p>

                        <p>Beispiel: Um die „Zeitschrift für Religionswissenschaft“ zu subskribieren, recherchieren Sie nach dem Titel
                            der Reihe. Wählen Sie im Anschluss unter
                            Medienart die Facette Zeitschrift aus. Subskribieren Sie die gewünschte Reihe durch Klick auf das
                            Symbol „Glocke“ (<i class="fa fa-fw fa-bell"></i>).</p>

                        <h3>Suchanfragen speichern</h3>
                        <p>Wenn Sie Ihre Suchanfragen dauerhaft verwenden wollen, können Sie sie in Ihrem Konto abspeichern. Diese haben Sie dann unter 
                           „Gespeicherte Suche“ in Ihrem Konto jederzeit zur Hand und können sie durch Anklicken erneut ausführen. Das lohnt sich für 
                           komplexe Abfragen oder für Themen, an denen Sie kontinuierlich interessiert sind. Auf diese Weise entdecken Sie leicht die neu 
                           erschienene Literatur zu einem bestimmten Thema oder Themengebiet.</p>

                        <h3>Favoriten speichern</h3>
                        <p>Speichern Sie interessante Titel direkt in Ihrem Konto ab. Damit stehen diese Ihnen dauerhaft zur Verfügung und Sie müssen 
                           nicht viel Zeit mit dem Wiederfinden verwenden. Ihre Favoriten können Sie in verschiedenen Listen speichern, die Sie selbst 
                           definieren. Auf diese Weise lassen sich interessante Titel beispielsweise bestimmten Forschungsprojekten oder Themen zuordnen. 
                           Diese Listen können Sie aus Ihrem Konto heraus auch exportieren, per Mail verschicken oder ausdrucken.</p>
                    </div>
                </div>
                <label for="post-3" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
