<style>
    .read-more-state {
        display: none;
    }

    .read-more-target {
        opacity: 0;
        max-height: 0;
        font-size: 0;
        transition: .25s ease;
    }

    .read-more-state:checked ~ .read-more-wrap .read-more-target {
        opacity: 1;
        font-size: inherit;
        max-height: 999em;
    }


    .read-more-state ~ .read-more-trigger:before {
        content: 'Mehr';
    }

    .read-more-state:checked ~ .read-more-trigger:before {
        content: 'Weniger';
    }

    .read-more-trigger {
        cursor: pointer;
        display: inline-block;
        padding: 0 .5em;
        color: #666;
        font-size: .9em;
        line-height: 2;
        border: 1px solid #ddd;
        border-radius: .25em;
    }
</style>


<div class="col-md-12" style="text-align:justify;">
    <h2>Liebe Nutzer von RelBib,</h2>
    <div class="post">
        <p>Wir freuen uns, Ihnen die &sbquo;Religionswissenschaftliche Bibliografie&lsquo;, kurz RelBib, vorstellen zu können. Sie ist die Alpha-Version einer vom Fachinformationsdienst (FID) &sbquo;Religionswissenschaft&lsquo; betreuten umfassenden bibliografischen Datenbank.</p>
        <p>Die Datenbank enthält derzeit <b><? include(dirname(__DIR__) . '/includes/relbib_journals_total.txt')?></b> Zeitschriften der Allgemeinen und Vergleichenden Religionswissenschaft, der Religionsgeschichte und einiger anderer kulturwissenschaftlicher Fach- und Themengebiete. Momentan werden aus dieser Anzahl <b><?include(dirname(__DIR__) . '/includes/relbib_journals_evaluated.txt')?></b> Zeitschriften auf Aufsatzebene erschlossen.  Diese Zahl wird sukzessive erhöht, Ziel ist es, alle oder die überwiegende Zahl der Zeitschriften auf Aufsatzebene zu erschließen und damit einzelne Aufsätze leicht auffindbar zu machen. Hier finden Sie eine <a href="<?='https://'.$_SERVER['SERVER_NAME'] . '/relbib_journals.pdf'?>" target="_blank"><b>Übersicht der Zeitschriften</b></a> und den Stand der Auswertung. Außer Zeitschriften(artikeln) enthält die Datenbank Nachweise zu religionswissenschaftlich relevanten Monografien.</p> 
        <p>Über den Link &bdquo;Verfügbarkeit&rdquo; kann rasch abgefragt werden, ob und wo eine Zeitschrift, ein Aufsatz oder ein Buch verfügbar ist. Wenn es lizenzrechtlich möglich ist, kann auf elektronisch vorliegende Texte direkt zugegriffen werden.</p>
        <p>RelBib ist ein kostenloses open access Angebot an die weltweite Fachcommunity der Religionswissenschaft. Herausgeber von RelBib ist die Universitätsbibliothek Tübingen. RelBib entsteht in Zusammenarbeit mit &sbquo;IxTheo&lsquo;, der theologischen Datenbank, die vom FID Theologie entwickelt und betreut wird. Durch die Zusammenarbeit können Synergien genutzt und gewährleistet werden, dass bei Bedarf für eine Recherche auch der theologische Inhalt der Datenbank hinzugeschaltet werden kann. </p>
        <p>Wir bitten um Verständnis, dass in einer Alpha-Version noch nicht alles fehlerfrei funktioniert. Wir wünschen
            Ihnen viel Freude beim Entdecken von RelBib und sind dankbar über Ihr Feedback!</p>
    </div>
</div>
<?
$panelId = 0;
$panelClass = "panel-default";
$panelWidth = "col-md-6";
?>
<h2 class="col-md-12 panel-group">RelBib entdecken</h2>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-search"></i> Suchen
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-1" />
                <div class="read-more-wrap">
                    <p>Starten Sie eine Suche über alle in RelBib enthaltenen Titel, indem Sie auf den Button „Suchen“
                        klicken.</p>
                    <div class="read-more-target">

                        <p>Grenzen Sie die Suche nun nach gewissen Kriterien ein, indem Sie entsprechende Facetten
                            auswählen.
                            Sie können z.B. gezielt den Medientyp „Nicht-Elektronisch“, die Medienart „Aufsatz“ und die Sprache
                            „Deutsch“ auswählen. Nun ist die Menge der Treffer auf diese Kriterien eingeschränkt</p>

                        <h3>Inhaltliche Suche</h3>
                        <h4>RelBib-Klassifikation</h4>
                        <p>
                            Nutzen Sie dazu die erweiterte Suche, indem Sie unter dem Suchschlitz auf „Erweiterte Suche“
                            klicken. Dort finden Sie u.a. die RelBib-Klassifikationen. Wählen Sie entsprechende Klassen
                            durch Anklicken aus. Mehrere Klassen können als Block durch das Halten der Umstell-Taste
                            beim Anklicken markiert werden. Mehrere einzelne Klassen werden durch das Halten der
                            „Kommando"-Taste (auf Apple Computer) oder der „Strg-Taste" (auf Windows Computer) beim
                            Anklicken markiert.
                        </p>
                        <p>Starten Sie durch Klick auf „Suche“ nun eine gezielte Suche nach den ausgewählten RelBib
                            Klassen.</p>

                        <h4>Verbale Suchbegriffe</h4>
                        <p>Tippen Sie den Suchbegriff in den Suchschlitz und belassen Sie den Suchaspekt auf „Alle Felder“.
                            Der
                            eingegebene Begriff wird dann in allen Suchfeldern gesucht.</p>
                        <p>Für eine inhaltliche Suche ist die Auswahl des Suchaspektes „Schlagwort“ von großem Nutzen. Hier
                            werden intellektuell vergebene Schlagwörter und Schlagwortfolgen durchsucht.</p>
                    </div>
                </div>
                <label for="post-1" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-list"></i> Browsen
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse ">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-2" />
                <div class="read-more-wrap">
                    <p>RelBib stellt drei verschiedene Arten des Browsens zur Verfügung. Sie finden den
                        Browsing
                        Modus durch Klick auf „Browsen“ unterhalb des Suchschlitzes.</p>
                    <div class="read-more-target">
                        <!-- Needed since otherwise the More-Button gets confused immediately before a heading -->
                        <div style="height: 0px;">&emsp;</div>
                        <h3>RelBib-Themen Browsing</h3>
                        <p>Es öffnet sich ein weiterer Suchschlitz, in den Sie Ihren Suchbegriff eingeben. Er dient als
                            Startpunkt des Browsens.</p>
                        <p>Beispiel 1: geben Sie den Begriff „Islam“ ein. Sie sehen dann eine spezielle Liste mit
                            Schlagwortfolgen, in denen der Begriff Islam vorkommt.</p>
                        <p>Beispiel 2: geben den Begriff „Islam“ und „Gott“ ein. Sie sehen dann eine spezielle Liste mit
                            Schlagwortfolgen, in denen der Begriff „Islam“ und „Gott“ vorkommt.</p>
                        <p>Wenn Sie rechts oben auf der Website die Sprache auf Englisch ändern, werden die Begriffe im
                            Englischen angezeigt, wenn sie in der Sprachkonkordanz vorhanden sind.</p>

                        <h3>Katalogbrowsen</h3>
                        <p>Die Standard-Browsing Funktion der Software von RelBib (VuFind) ermöglicht das Browsen in
                            verschiedenen Feldern: DDC-Klassifikation, RelBib-Klassifikation, Thema (Schlagwort), Verfasser
                            und
                            Verlag. In einem weiteren Schritt kann hier das Browsing durch andere Felder eingeschränkt werden.</p>
                        <p>Beispiel: Wählen Sie „Verfasser“, dann „Nach RelBib-Klassifikation“, dann „AB Religionsphilosophie“
                            aus.
                            Sie sehen dann eine Liste von Autoren, die in diesem Bereich publiziert haben,
                            sortiert nach Häufigkeit der Titel in RelBib.</p>

                        <h3>Alphabetisch browsen</h3>
                        <p>Hier können Sie bestimmen, an welcher Stelle des Alphabets Sie in das Browsing einsteigen wollen.
                            Nach der Auswahl des Browsingaspektes (möglich sind „Thema“, Verfasser, Titel und
                            DDC-Klassifikation) geben Sie den Buchstaben ein, ab dem das Browsing starten soll.</p>
                        <p>Beispiel 1: Wählen Sie „Nach Verfasser“ und geben Sie ein: ab „Z“. Es werden dann alle Verfasser
                            aufgelistet, die mit dem Buchstaben Z beginnen.</p>
                        <p>Beispiel 2: Wählen Sie „Nach Titel“ und geben Sie ein: ab „Tr“. Es werden dann alle Titel
                            aufgelistet, die mit der Buchstabenfolge Tr beginnen.</p>
                    </div>
                </div>
                <label for="post-2" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-child"></i> Personalisierung
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-3" />
                <div class="read-more-wrap">
                    <p>Viele nützliche Funktionen stehen Ihnen zur Verfügung, wenn Sie einen persönlichen Account
                        anlegen.
                        Nach einer einmaligen Registrierung können Sie sich in Ihren Account einloggen.
                    <div class="read-more-target">
                        Um sich zu registrieren oder einzuloggen klicken Sie auf den Link „Login“ rechts oben.</p>
                        <p>Durch Klick auf „Ihr Konto“ kommen Sie in Ihren personalisierten Bereich. Dort stehen Ihnen u.a.
                            folgende Funktionen zur Verfügung:</p>

                        <h3>Alerting-Funktion</h3>
                        <p>Die Alerting Funktion unterrichtet Sie über neu erschienene Aufsätze aus Zeitschriften und neu
                            erschienene Bände in Reihen und Fortsetzungen. Sie können frei entscheiden, in welchen Fällen
                            Sie
                            eine Benachrichtigung wünschen.</p>
                        <p>Um eine Zeitschrift oder eine Reihe für das Alerting auszuwählen, müssen Sie die Gesamtaufnahme
                            der
                            Zeitschrift oder Reihe subskribieren. Klicken Sie dazu auf das Symbol "Glocke", die Sie rechts
                            im
                            entsprechenden Datensatz sehen. In Ihrem Konto können Sie die Subskriptionen verwalten.</p>

                        <p>Beispiel: Um die „Zeitschrift für Religionswissenschaft“ zu subskribieren, recherchieren Sie nach dem Titel
                            der Reihe. Wählen Sie im Anschluss unter
                            Medienart die Facette Zeitschrift aus. Subskribieren Sie die gewünschte Reihe durch Klick auf das
                            Symbol „Glocke“</p>

                        <h3>Suchanfragen speichern</h3>
                        <p>Ihre aktuellen Suchanfragen werden in der Suchhistorie temporär gespeichert. Wenn Sie die
                            Suchanfragen dauerhaft verwenden wollen, können Sie sie in Ihrem Konto abspeichern. Sie stehen
                            dann
                            in Ihrem Konto dauerhaft zur Verfügung und können durch Anklicken erneut ausgeführt werden. Das
                            lohnt sich für komplexe Abfragen oder für Themen, an denen Sie kontinuierlich interessiert sind.
                            Auf
                            diese Weise entdecken Sie leicht die neu erschienene Literatur zu einem bestimmten Thema oder
                            Themengebiet.</p>

                        <h3>Favoriten speichern</h3>
                        <p>Speichern Sie interessante Titel direkt in Ihrem Konto ab. Damit stehen Sie Ihnen dauerhaft zur
                            Verfügung und Sie müssen nicht viel Zeit mit dem Wiederfinden verwenden. Damit die Favoriten
                            geordnet werden können, werden Sie in Listen gespeichert, die Sie definieren können. So können
                            interessante Titel gewissen Forschungsprojekten oder Themen zugeordnet werden.</p>
                        <p>Aus Ihrem Konto heraus können Sie Favoriten exportieren, per Mail verschicken oder
                            Ausdrucken.</p>
                    </div>
                </div>
                <label for="post-3" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
