
<div class="col-md-12" style="text-align:justify;">
    <h2>Dear users of the Index Theologicus</h2>
    <div class="post">
        <p>we are pleased to present to you the alpha version of the new IxTheo.</p>
        <p>The new IxTheo is a comprehensive bibliography for theology and religious studies. It is now possible to search not only for articles, 
           but also for monographs, databases and relevant Internet  links. A selection of review journals is now also included. 
           When the relevant licenses permit it, it is possible to access directly the complete text of the articles, reviews and books.</p>
        <p>The new IxTheo remains a free and open access service to the worldwide scholarly community. The editors of the IxTheo are the Universitätsbibliothek Tübingen 
           (library of the university of Tübingen) as well as the Evangelisch-Theologische Fakultät Tübingen (the protestant faculty of theology of the university of Tübingen) 
           und die Katholisch-Theologische Fakultät Tübingen (the catholic faculty of theology of the same university).</p>
        <p>We apologize in advance for any errors which might come up at this early stage of development. We wish you an enjoyable experience as you explore the new 
           IxTheo and we would be glad to get your feedback!</p>
    </div>
</div>
<?
$panelId = 0;
$panelClass = "panel-default";
$panelWidth = "col-md-6";
?>
<h2 class="col-md-12 panel-group">Discover IxTheo</h2>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-search"></i> Search
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <p>You can start a search on all the titles catalogued in the IxTheo by clicking on the “Find” button. You will then find over 1.6 Million titles.</p>

                <p>You may narrow down the search according to certain criteria by selecting the corresponding facets. For example, you can select the “Electronic” 
                   media type, the “Article” format and the “German” language. The number of titles is now reduced to about 3000.</p>

                <h3>Search by content</h3>
                <h4>IxTheo Classification</h4>
                <p>For this purpose, you can use the advanced search by clicking on “advanced” underneath the search field. There, you will find the IxTheo 
                   classifications among others. You may select the corresponding facets by clicking on them. You may also select a range of facets by holding 
                   the “shift”-button while clicking on the start and finishing items of the range. If you want to select several individual facets, just hold 
                   the “Command”-button (on Apple computers) or the “Strg”-button (on Windows computers) while clicking on each item. </p>
                <p>Starten Sie durch Klick auf „Suche“ nun eine gezielte Suche nach den ausgewählten IxTheo
                    Klassen.</p>

                <h3>Search Terms</h3>
                <p>Enter the term in the search field and leave the search category on “All Fields”. IxTheo will then search for the term you entered in all search fields.</p>
                <p>To conduct a search by content, you may find the search category “Subject” very useful. In this case, the search is conducted on subject headings assigned by our staff.</p>
            </div>
        </div>
    </div>
</div>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-list"></i> Browsing
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse ">
            <div class="panel-body">
                <p>The new IxTheo offers three different ways to browse:</p>

                <h3>IxTheo - Find Topic</h3>
                <p>When you select this option, it opens an additional search field in which you may enter your search term. This term is then used as the starting point of the browsing.</p>
                <p>1st example: enter the term “God”. You will then see a list of subject heading strings which contain the word “God”.</p>
                <p>2nd example: enter the terms “God” and “Bible”. You will then see a list of subject heading strings which contain the words “God” and “Bible”.</p>
                <p>If you change the language of the website to German, the terms are shown in German if they are found in the language concordance.</p>

                <h3>Browse the Catalogue</h3>
                <p>The standard browsing function of the software used by IxTheo (VuFind) makes it possible to browse through various fields: DDC-Classification, 
                   IxTheo-Classification, Topic (subject heading), Author and Publisher. In a further step, you may determine the items you wish to browse by using other fields.</p>
                <p>For example, select “Author”, then “By IxTheo-Classification”, then “HB Old Testament”. You will then see a list of authors who have worked in the field 
                   of Old Testament research, sorted according to the number of their works catalogued in the IxTheo.</p>

                <h3>Browse Alphabetically</h3>
                <p>With this search option, you can decide at which point in the alphabet you would like to start the search. After you’ve selected the 
                   browsing category (you may select among Topic, Author, Title or DDC-Classification), enter the letter at which you would like to start to browse.</p>
                <p>1st example: select “By Author” and enter “Z” next to “starting from”. You will then get a list of all authors whose name starts with the letter “Z”.</p>
                <p>2nd example: select “By Title” and enter “Tr” next to “starting from”. You will then get a list of all the titles which start with the letter “Tr”.</p></div>
        </div>
    </div>
</div>
<div class="col-md-4" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-child"></i> Personalized searches
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <p>Many useful functions are at your disposal when you create a personal account. Once you’ve registered, you may log into your account by clicking 
                   on the link called “Login” on the top right corner.</p>
                <p>By clicking on “Your account”, you come into your personalized area. You may then use the following functions:</p>

                <h3>Alerting function</h3>
                <p>The alerting function lets you know when new articles from certain journals and new volumes from certain series are available. You may decide in which 
                   cases you would like to get a corresponding message.</p>
                <p>In order to receive such “alerts” for a journal or a series, you must mark the corresponding entry for the journal or series as a whole. You can do this 
                   by clicking on the “Bell” symbol which you will find on the right side of the corresponding entry. You can manage the list of publications marked for an 
                   alert in your account under the heading “alert list”.</p>

                <p>1st example: in order to get alerts for the Theologische Quartalschrift, search for the title of this journal or enter the abbreviation “ThQ” 
                   in the search field. Then select under “Format” the “Journal” facet. You will get two entries as a result: one for the printed, and one for the 
                   online version of the journal. In this case, it would be preferable to mark both media types for an alert.</p>

                <p>2nd example: in order to get alerts for the series “ Wissenschaftliche Untersuchungen zum Neuen Testament”, search for the title of the series or
                   enter the abbreviation “WUNT” in the search field. You will then get a list of entries. Mark the series by clicking on the “Bell” symbol.</p>

                <p>We will try to make the selection of journals and series for the alerting function more user-friendly in the future. We plan to offer the possibility 
                   of marking whole blocks of journals which are catalogued in the IxTheo according to their academic discipline.</p>

                <h3>Saving search requests</h3>
                <p>Your current search requests are temporarily stored in the search history. If you would like to have permanent access to certain search requests, 
                   you can save them permanently in your account. You may then use them again through a simple mouse click. This feature might be useful for complex 
                   requests or for subjects in which you have a continuing interest. In this way, you will find the latest literature on a given subject or area of knowledge.</p>

                <h3>Saving favorites</h3>
                <p>You can save interesting titles directly in your account. They are then permanently accessible, and you don’t have to waste any time searching for them again. 
                   In order to sort such “favorites”, they are kept in lists which you define yourself. In this way, you can assign interesting titles to specific research 
                   projects or subjects.</p>
                <p>In your account, you can also export your favorites, send them per e-mail or print them.</p>
            </div>
        </div>
    </div>
</div>
