What are the next steps?
   1st) We will now try to acquire the desired book
   2nd) If the book cannot be acquired, we will inform you by email.
   3rd) After the ingress of the book to the Tübingen University Library we will directly send it to you if you provide a delivery address.
   4th) At the end of your loan period you send back the book to us. Details are included with the book.
   5th) If you have not provided a delivery address we will will inform you when the book arrives at the Tübingen University Library.
   You can then immediately trigger an interlibrary loan.
