<p>Dear IxTheo User,</p>
<p>By the Patron Driven Acquisition (PDA) programme of the Fachinformationsdienst (FID) Theology you can initiate the purchase of books that have not yet been available for loan so far.</p>

<p>If you enter your address in the area below we will try directly send the book. Please note that direct delivery is only possible within Germany. If you come from another country you have to order the book through an interlibrary loan.
</p>What are the next steps?</p>
<ol>
    <li>We will now try to acquire the desired book
    <li>If the book cannot be acquired, we will inform you by email.
    <li>After the ingress of the book to the Tübingen University Library we will directly send it to you if you provide a delivery address.
    <li> At the end of your loan period you send back the book to us. Details are included with the book.
    <li> If you do not provide a delivery address we will will inform you about the ingress to the Tübingen University Library.
         You can then immediately trigger an interlibrary loan.
</ol>

<p>How long can you loan a book?<br>The loan period is four weeks.</p>

<p>You are about to trigger the acquisiton of the following book:</p>
