<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#KeineFAQ">
            <h4 class="panel-title">
                Warum gibt es keine FAQs?
            </h4>
        </A>
    </div>
    <div id="KeineFAQ" class="panel-collapse collapse">
        <div class="panel-body">
            <p> Dieses Projekt befindet sich noch in der Entwicklungsphase. Bis jetzt wurden noch keine FAQs geschrieben.
            </p>
        </div>
    </div>
</div>