<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#KeineFAQ">
            <h4 class="panel-title">
                Why can't I find any FAQs?
            </h4>
        </A>
    </div>
    <div id="KeineFAQ" class="panel-collapse collapse">
        <div class="panel-body">
            <p> This project is in development. FAQs weren't written until now.
            </p>
        </div>
    </div>
</div>