<? $formats = $this->driver->getFormats(); if (!empty($formats) && ( in_array("Article", $formats) || in_array("Journal", $formats))): ?>
  <?$issn = $this->driver->tryMethod('getCleanISSN')?>
  <?$issn = (substr_count($issn, "-") == 0) ? implode("-", str_split($issn, 4)) : $issn?>
    <?if (!empty($issn)): ?>
      <tr>
        <th>Journals Online &amp; Print:</th>
        <td>
          <?php
            $genre = (in_array('Article', $formats)) ? "article" : "journal";
            $article_information = "";
            if ($genre == "article") {
                $volume = $this->escapeHtml($this->driver->getVolume());
                if (!empty($volume))
                    $article_information .= "&volume=" . $volume;
                $issue = $this->escapeHtml($this->driver->getIssue());
                if (!empty($issue))
                    $article_information .= "&issue=" . str_replace("=", "%20", $issue);
                $year = $this->escapeHtml($this->driver->getYear());
                if (!empty($year))
                    $article_information .= "&date=" . $year;
                $pages = $this->escapeHtml(str_replace(" ", "", $this->driver->getPages()));
                if (!empty($pages))
                    $article_information .= "&pages=" . $pages;
            }
          ?>
          <div style="color:grey" id="jop_icons"><a href=http://services.dnb.de/fize-service/gvr/html-service.htm?sid=bib:tueb&issn=<?=$this->escapeHtml($issn)?>&genre=<?=$genre?><?=$article_information?>>
             <img src=<?=$this->url('home') ?>proxy/load?url=http%3A%2F%2Fservices.dnb.de%2Ffize-service%2Fgvr%2Ficon%3Fsid%3Dbib%3Atueb%26issn%3D<?=$this->escapeHtml($issn)?>&genre=<?=$genre?><?=$article_information?>%26pid%3Dclient_ip%253D<?=$_SERVER['REMOTE_ADDR'];?> alt="JOP Icons should be here">
</a>
</div>
          <div style="color:grey" id="jop_place_holder"><?=$this->transEsc("Loading")?>...</div>
        </td>
      </tr>
      <script type="text/javascript" language="javascript">
        var genre  = ("<?=in_array('Article', $formats)?>" ? "article" : "journal");
        var article_information = ("");
        if (genre == "article") {
          article_information = ("<?=$article_information?>");
        }
        $.ajax({
          type: "GET",
          url: "<?=$this->url('home') ?>proxy/load?url=http%3A%2F%2Fservices.dnb.de%2Ffize-service%2Fgvr%2Ffull.xml%3Fsid%3Dbib%3Atueb%26issn%3D<?=$this->escapeHtml($issn)?>%26genre%3D"+genre+article_information+"%26pid%3Dclient_ip%253D<?=$_SERVER['REMOTE_ADDR'];?>",
          dataType: "xml",
          success: function(xml) {
            $(document).ready(function() {
              var replacement = "";
              var filter = [];
              $(xml).find('Result').each(function(index, value) {
                var state = $(this).attr("state");
                if (state >= 0 && state <= 3) {
                  var accessURL = $(value).find('AccessURL').first().text();
                  if (accessURL) {
                    if (filter[accessURL] != 1) {
                      if (replacement)
                        replacement += '<br />';
                      replacement += '<a href="' + accessURL + '">'
                                     + '<?=$this->transEsc("Available online")?>' + '.</a>';
                      filter[accessURL] = 1;
                    }
                  } else {  // Hopefully available in print!
                    var location = $(value).find('Location').first().text();
                    var call_number = $(value).find('Signature').first().text();
                    var label = location;
                    if (call_number)
                      label += " (" + call_number + ")";
                    if (filter[label] != 1) {
                      if (replacement)
                        replacement += '<br />';
                      replacement += label;
                      filter[label] = 1;
                    }
                  }
                }
                else if (state == 4 || state == 10) {
                  var access_url = 'http://services.dnb.de/fize-service/gvr/html-service.htm?sid=bib:tueb&issn=' + 
                                  '<?=$this->escapeHtml($issn)?>' + '&genre=' + '<?=$genre?>' + 
                                  '<?=$article_information?>';
                  if (replacement == ""){
                     replacement = '<a href="' + access_url + '">' + '<?=$this->transEsc("Check Availability")?>' +'</a>';
                     // We get an 1x1 pixel gif from JOP that can be seen as an empty line
                     // => remove it
                     $("#jop_icons").remove();
                  }
                }
              });
              if (replacement != ""){
                $("#jop_place_holder").each(function() {
                  $(this).replaceWith(replacement);
                });
              } else {
                $("#jop_place_holder").each(function() {
                  $(this).replaceWith('<?=$this->transEsc("Not available")?>.');
                })
              }
            });
          }, // end success
          error: function(xhr, ajaxOptions, thrownError) {
            $("#jop_place_holder").each(function() {
              $(this).replaceWith('Invalid server response. (JOP server down?)');
            })
            if (window.console && window.console.log) {
              console.log("Status: " + xhr.status + ", Error: " + thrownError);
            }
          }
        }); // end ajax
      </script>
    <? endif; ?>
  <? endif; ?>
