<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));



  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
?>

<div class="searchHomeContent">
  <div class="well well-lg clearfix" role="search">
  <? 
	if(isset($this->results)){

	    $lookfor = $this->results->getUrlQuery()->isQuerySuppressed() ? '' : $this->params->getDisplayQuery();
        }

      $this->layout()->searchbox = $this->context($this)->renderInContext(
      'keywordchainsearch/searchbox.phtml',
      array(
        'lookfor' => $lookfor,
        'searchIndex' => isset($this->params) ? 
				$this->params->getSearchHandler() : '',
        'searchType' => isset($this->params) ?  
				$this->params->getSearchType() : '' ,
        'searchId' => isset($this->results) ?
				$this->results->getSearchId() : '', 
        'searchClassId' => isset($this->params) ? 
				$this->params->getsearchClassId() : '',
        'checkboxFilters' => isset($this->params) ? 
				$this->params->getCheckboxFacets() : '',
        'filterList' => $this->params->getFilters(),
        'hasDefaultsApplied' => isset($this->params) ? 
			$this->params->hasDefaultsApplied() : '',
        'selectedShards' => isset($this->params) ? 
		 $this->params->getSelectedShards() : ''
      )
    ); ?> 
  </div>
</div>

