<div class="feedback-box">
    <h2>What do you think?</h2>

    <div class="radio">
        <label><input type="radio" class="feedback-radio" name="feedback-radio" onclick="setMoode('1')">It was great</label>
    </div>
    <div class="radio">
        <label><input type="radio" class="feedback-radio" name="feedback-radio" onclick="setMoode('2')">It was okay</label>
    </div>
    <div class="radio">
        <label><input type="radio" class="feedback-radio" name="feedback-radio" onclick="setMoode('3')">It was disappointing</label>
    </div>
    <div id="feedback-form">
        <div id="feedback-message"></div>
        <input id="feedback-message-input" type="hidden" name="moode" value="0"/>
        <textarea id="feedback-message-text"></textarea><br>
        <button id="feedback-submit">Submit feedback</button>
    </div>
</div>
