<div style="display:none;" id="feedback_custom_html">
    <?=$this->render('feedback/feedback-box.phtml')?>
</div>

<script>
    var custom_html = $("div#feedback_custom_html").html();

    $(document).ready(function () {
        //set up some minimal options for the feedback_me plugin
        fm_options = {
            bootstrap: true,
            title_label : "",
            trigger_label: "<?=$this->transEsc("Feedback");?>",
            position: 'right-bottom',
            show_form: false,
            custom_html: custom_html,
            delayed_close : true,
            delayed_options : {
                delay_success_milliseconds : 2000,
                delay_fail_milliseconds : 2000,
                sending : "<?=$this->transEsc("Sending...");?>",
                send_fail : "<?=$this->transEsc("Sending failed.");?>",
                send_success : "<?=$this->transEsc("Feedback sent.");?>",
                fail_color : undefined,
                success_color : undefined,
                custom_html_success: undefined,
                custom_html_fail: undefined
            }
        };

        //init feedback_me plugin
        fm.init(fm_options);

        setMood('0');
        $('#feedback-submit').click(function(event) {
            var mood = $("#feedback_radio1:checked").val() ? 1 : 
                           ($("#feedback_radio2:checked").val() ? 2 : 
                                ($("#feedback_radio3:checked").val() ? 3 : 
                                    ($("#feedback_radio4:checked").val() ? 4 : 0)));
                                      
            var message = $("textarea#feedback-message-text").val();
            var email = $("#feedback-message-email").val();
            if (mood == 0 && !message) {
                return;
            }
            $.ajax({url: "/ajax/feedback",
                type: "POST",
                data: {"mood": mood, "message": message, "email": email},
                success: function(result) {
                    setMood('0');
                    $("textarea#feedback-message-text").val("");
                    $(".feedback-radio").removeAttr('checked');
                    fm.stopPropagation(event);
                    fm.triggerAction(event,'right-bottom');
                }
            });
        });
    });

    function setMood(mood) {
        if (mood == '1') {
            $("#feedback-message").html('<?=$this->transEsc("Thanks. Anything else you’d like to add?");?>');
        } else if (mood == '2') {
            $("#feedback-message").html('<?=$this->transEsc("What could we have changed to make it even better?");?>');
        } else if (mood == '3') {
            $("#feedback-message").html('<?=$this->transEsc("Sorry to hear that. How can we improve?");?>');
        } else if (mood == '4') {
            $("#feedback-message").html('<?=$this->transEsc("Please describe the error");?>');
        } else {
            $("#feedback-message").html("&nbsp;");
        }
    }
    
    function toggle() {
        var radio = $("input#feedback_radio1");
      (radio.checked) ? radio.checked = false : radio.checked = true;
    }
</script>
