<? if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?>. <? endif; ?>
&quot;<?=$this->title?><? if ($this->periodAfterTitle): ?>.<? endif ?>&quot; 
<span style="font-style:italic;"><?=$this->escapeHtml($this->journal)?></span> 
<? if (!empty($this->numberAndDate)): ?><?=$this->escapeHtml($this->numberAndDate)?><? if (!empty($this->pageRange)): ?>, <? endif; ?><? endif; ?>
<? if (!empty($this->pageRange)) echo strstr($this->pageRange, '-') ? 'pp. ' : 'p. '; ?>
<?=$this->escapeHtml($this->pageRange)?>. <? if (isset($this->doi)): ?>doi:<?=$this->escapeHtml($this->doi)?><? endif; ?>
