<? $this->headTitle($this->translate('FAQ')); ?>
<? foreach ($topics as $topic): ?>
    <? if ($help = $this->helpText()->render($topic, ['panelClass' => 'panel-default'], "FAQTranslations")): ?>
        <? foreach ($this->helpText()->getWarnings() as $warning): ?>
            <p class="alert alert-warning"><?=$this->transEsc($warning)?></p>
        <? endforeach; ?>
        <?=$help?>
    <? else: ?>
        <p class="alert alert-danger"><?=$this->transEsc('help_page_missing')?></p>
    <? endif; ?>
<? endforeach; ?>
<? if (empty($topic)): ?>
    <h1>Nicht oft gefragte Fragen... (Platzhalter)</h1>
    <ul><li> 	Welchen Shampoo hilft gegen Nikoläuse?
    </li><li> 	Wenn man einen Schlumpf würgt, welche Farbe hat er dann?
    </li><li> 	Wenn die Stiftung Warentest Vibratoren testet, ist dann ‘befriedigend’ besser als ‘gut’?
    </li><li> 	Woran ist das tote Meer gestorben?
    </li><li> 	Was ist die Mehrzahl von "Mehrzahl"?
    </li><li> 	Was ist das Gegenteil von "Gegenteil"?
    </li><li> 	Dürfen Vegetarier Schmetterlinge im Bauch haben?
    </li><li> 	Macht man den Meeresspiegel kaputt wenn man in See sticht?
    </li><li> 	Was passiert wenn man sich an Witzen zwei mal halb tot lacht?
    </li><li> 	Wenn Schweineschnitzel aus Schwein bestehen, aus was sind dann Kinderschnitzel?
    </li><li> 	Wie sucht man eine Suchmachine?
    </li><li> 	Was für einen Sehtest machen Analphabeten?
    </li><li> 	Haben Schafe, die an einem Hang grasen, vorne oder hinten kürzere Beine?
    </li><li> 	Kann man ein Damenfahrrad herrenlos umherstehen lassen?
    </li><li> 	warum geht der uhrzeiger immer nur rechts rumm und nicht links herum ?
    </li><li> 	warum ist der himmel oben und nicht unten ?
    </li><li> 	warum steht auf tetrapacks immer hier öffnen und nicht da öffnen?
    </li><li> 	Schmecken Amphibien nach Fisch oder Fleisch?
    </li><li> 	Warum winken einem die Leute auf einem Dampfer zurück wenn man Ihnen winkt und bei einem Zug passiert überhaupt nix?
    </li><li> 	Wie überzeugt man einen Rhetorikprofesor?
    </li><li> 	Wer bringt dem Storch die Kinder?
    </li><li> 	Wenn ein Mensch sich gruselt, beommt er eine Gänsehaut. Wenn eine Gans sich gruselt, was bekommt die dann?
    </li><li> 	Wenn Menschen Schmetterlinge im Bauch haben, was haben dann Schmetterlinge im Bauch?
    </li><li> 	Schmeckt Cola besser als aus dem Glas?
    </li><li> 	Wie erklärt man einen Bekloppten, das er Bekloppt ist?
    </li><li> 	Warum haben 24 Stunden Tankstellen Schlösser?
    </li><li> 	Warum sind Todesspritzen desinfiziert?
    </li><li> 	Schwitzen Kühe unter ihren schwarzen Flecken mehr als unter ihren weißen?
    </li><li> 	Wo kämen wir denn hin, wenn jeder sagen würde wo kämen wir hin, aber niemand gehen würde um zu sehen wohin wir kämen wenn wir gingen?
    </li><li> 	Warum können wir uns nicht selber kitzeln?
    </li><li> 	Kommen schnecken mit ihren Häusern zur Welt?
    </li><li> 	Habe Hühner einen Bauchnabel?
    </li><li> 	Wieso hat Tarzan keinen Bart?
    </li><li> 	Sind Vegetarier, die eine Fleischtomate essen noch Vegetarier?
    </li><li> 	brauchen Fische Schuppenschampoo ?
    </li><li> 	warum tragen Kamikazie-Piloten eigentlich Sturzhelme ?
    </li><li> 	warum rosten Fische nicht ?
    </li><li> 	Wenn man Fernsehen guckt verbraucht man weniger Energie als wenn man schläft, was passiert, wenn man vorm Fernseher einschläft???
    </li><li> 	Warum is die Banane Krumm?
    </li><li> 	Wenn Eva aus einer Rippe von Adam besteht, wie kommt es dass sie selber welche hat?
    </li><li> 	Kratzen Wolkenkratzer Wolken? Und tun sie das in Amerika mit dem Himmel (Skyscraper)
    </li><li> 	Würde es eine Sintflut auslösen wenn die ganze Welt ihren Wagen wäscht oder picknicken geht?
    </li><li> 	Warum heisst die Feuerwehr Feurwehr, wo sie doch mit Wasser spritzen?
    </li><li> 	Warum können Flammen züngeln?
    </li><li> 	Eine Thermoskanne hält im Winter warm, und im Sommer kalt.
    </li><li> 	Doch woher weiß sie, wann Sommer und wann Winter ist?
    </li><li> 	Ist der Begriff Selbsthilfegruppe nicht widersinnig?
    </li><li> 	Warum gibt es in Flugzeugen Schwimmwesten statt Fallschirme?
    </li><li> 	Wenn ein Fisch und ein Vogel sich verlieben, wo bauen sie ihr Nest???
    </li><li> 	Was ist grün, rund, essbar und macht kleine blaue geräusche? - genau.
    </li><li> 	Könnte der Zweck des Menschen nicht auch der Transport von Wasser auf Berge sein?
    </li><li> 	Warum steht auf der "Black Box" "Bitte nicht öffnen?"
    </li><li> 	Warum ist "Abkürzung" länger als "Umweg" ?
    </li><li> 	Ist es mit dem Fahrrad kürzer als durch den wald?
    </li><li> 	Sind Rote Schuhe Wärmer als hohe?
    </li><li> 	Ist es Nachts kälter als draußen?
    </li><li> 	Wen ein Schizophrener unter einer Multiplen-Persönlichkeitsstörung leidet und Selbstmord begeht, ist das dann ein Massenmord?
    </li><li> 	Warum wird immer über die Dummen geschimpft? Wenn es keine Dummen gäbe, wüßten die Intelligenten doch nicht, dass sie schlau sind?
    </li><li> 	Muß man sich vor "ausschlagenden" Bäumen hüten?
    </li><li> 	Wie kommt das Rasen nicht betreten Schild auf den Rasen
    </li><li> 	Haben Zebras eigentlich weisse oder schwarze Streifen?
    </li><li> 	Wenn die sog. "Black Box" eines Flugzeugs unzerstörbar ist, wieso baut man dann nicht das ganze Flugzeug aus dem Material?
    </li><li> 	Auf den meisten Verbrauchsgütern steht "Hier Öffnen". Was schreibt das Protokoll vor, wenn dort stehen würde: "Woanders öffnen"?
    </li><li> 	Wenn man in einem Fluggerät sitzen würde, das mit Lichtgeschwindigkeit fliegt, was würde passieren, wenn man die Scheinwerfer einschaltet?
    </li><li> 	Warum gibt es in Flugzeugen Schwimmwesten statt Fallschirme?
    </li><li> 	Haben blinde Eskimos Blinden-Schlittenhunde?
    </li><li> 	Warum steht auf Sauerrahm-Bechern ein Verfallsdatum?
    </li><li> 	Warum benutzt man für "Tödliche Injektionen" in den Staaten sterilisierte Spritzen/Nadeln?
    </li><li> 	Wieso hat eine 24-Stunden-Tankstelle Tür-Schlösser?
    </li><li> 	Wenn nichts an Teflon haftet, wieso haftet es an der Pfanne?
    </li><li> 	Warum gehen Frauen niemals alleine aufs Klo?
    </li><li> 	Wie würden Stühle aussehen, wenn wir die Kniescheiben hinten hätten?
    </li><li> 	Leben Verheiratete länger oder kommt ihnen das nur so vor?
    </li><li> 	Warum besteht Zitronenlimonade größtenteils aus künstlichen Zutaten, während in Geschirrspülmittel richtiger Zitronensaft drin ist?
    </li><li> 	Warum glauben einem Leute sofort, wenn man ihnen sagt, dass es am Himmel 400 Billionen Sterne gibt, aber wenn man ihnen sagt, dass die Bank frisch gestrichen ist, müssen sie draufpatschen?
    </li><li> 	Wenn Superkleber wirklich überall klebt, warum dann nicht auf der Innenseite der Tube?
    </li><li> 	Wie heißen die teile die im Supermarkt die Ware trennen?
    </li><li> 	Wie heißen die Plastik Dinger am Ende von den Schnürsenkeln?
    </li><li> 	Warum laufen Nasen, während Füße riechen?
    </li><li> 	Gibt es ein anderes Wort für Synonym?
    </li><li> 	Warum ist einsilbig dreisilbig?
    </li><li> 	Wie kommt ein Schneepflugfahrer morgens zur Arbeit?
    </li><li> 	Warum gibt es kein Katzenfutter mit Mausgeschmack?
    </li><li> 	Mit welcher Geschwindigkeit breitet sich das Dunkel aus?
    </li><li> 	Wie packt man Styroporkügelchen ein, wenn man sie verschickt?
    </li><li> 	Warum muß man für den Besuch beim Hellseher einen Termin haben?
    </li><li> 	Warum ist nie besetzt, wenn man die falsche Nummer wählt?
    </li><li> 	Wenn Schwimmen schlank macht, was machen Blauwale falsch?
    </li><li> 	Kann man einen Schizophrenen, der mit Selbstmord droht, wegen Geiselnahme festnehmen?
    </li><li> 	Wohin geht das Licht im Kühlschrank, wenn man die Tür zumacht?
    </li><li> 	Meinst du, ein Brandfallopfer bekommt im Krematorium Rabatt?
    </li><li> 	Wenn man einen Schlumpf würgt, welche Farbe bekommt er dann?
    </li><li> 	Wie kommen die "Rasen betreten verboten"-Schilder in die Mitte des Rasens?
    </li><li> 	Haben Analphabeten genau so viel Spaß mit einer Buchstabensuppe?
    </li><li> 	Als der Mensch entdeckte, daß Kühe Milch geben - was tat er dann gerade?
    </li><li> 	Wenn Chinesen auf Hochzeiten Reis werfen, werfen Mexikaner dann Kakteen?
    </li><li> 	Falls ein Wort falsch geschrieben im Wörterbuch steht, werden wir das je erfahren?
    </li><li> 	Warum ist "Abkürzung" so ein langes Wort?
    </li><li> 	Wie merkt man, daß unsichtbare Tinte aus ist?
    </li><li> 	Warum hat Noah die zwei Stechmücken nicht erschlagen?
    </li><li> 	Wenn Hasenpfoten Glück bringen, hat der Hase dann auch Glück gehabt?
    </li><li> 	Ein Butterbrot landet immer auf der Butterseite. Eine Katze landet immer auf den Pfoten. Was passiert, wenn man einer Katze Butter auf den Rücken schmiert?
    </li><li> 	Wenn der Mensch eine Weiterentwicklung des Affen ist, warum gibt's dann noch Affen?
    </li><li> 	Bekommen die Arbeitnehmer von Teekanne auch eine Kaffeepause?
    </li><li> 	Warum schrumpfen Schafe nicht wenn es regnet?
    </li><li> 	Wenn es heute null Grad hat, und es wird morgen zwei mal so kalt, wie viel Grad hat es dann morgen?
    </li><li> 	Warum muß der Deckel von einem Sarg zugenagelt werden?
    </li><li> 	Was zählen Schafe, wenn sie nicht schlafen können?
    </li><li> 	Olivenöl kommt von Oliven, Maisöl kommt von Mais. Woher kommt Babyöl?
    </li><li> 	Wenn Dich ein Taxichauffeur im Rückwärtsgang nach Hause bringt, muß er dann Dir was bezahlen?
    </li><li> 	Wie weiß ein Blinder, daß er fertig ist mit Hintern putzen?
    </li><li> 	Wenn es Lebkuchen gibt, warum gibt's keinen Todkuchen?
    </li><li> 	Warum sieht jeder, wenn ich besoffen bin, aber keiner das ich Durst habe?
    </li><li> 	Hat der Besitzer eines Survival-Knives wirklich alles im Griff?
    </li><li> 	Findet der Birkenspanner die Birke wirklich so aufregend?
    </ul>
    <a href="http://www.malkavian.de/malk/fragen.html">Quelle</a>
<? endif; ?>

